id = "stata"
name = "Stata"
description = "Stata language support for Zed"
version = "0.5.11"
schema_version = 1
authors = ["Jonathan Marc Bearak"]
repository = "https://github.com/jbearak/zed-stata"
themes = []
icon_themes = []
languages = ["languages/stata"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.stata]
repository = "https://github.com/jbearak/tree-sitter-stata"
rev = "a47d1bb771d45da5058953f5d935759fac16d854"

[language_servers.sight]
name = "Sight"
languages = ["Stata"]
